// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/editor.dart';
import 'api/rope.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEditorInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1740630692;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'code_forge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiEditorLayoutMapClear({required LayoutMap that});

  LayoutMap crateApiEditorLayoutMapNew();

  void crateApiEditorLayoutMapPushLine({
    required LayoutMap that,
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  });

  List<String> crateApiRopeRopeBridgeCachedLines({required RopeBridge that});

  List<String> crateApiRopeRopeBridgeCachedLinesRange({
    required RopeBridge that,
    required BigInt startLine,
    required BigInt endLine,
  });

  String crateApiRopeRopeBridgeCharAt({
    required RopeBridge that,
    required BigInt position,
  });

  BigInt crateApiRopeRopeBridgeCharToLine({
    required RopeBridge that,
    required BigInt charIdx,
  });

  RopeBridge crateApiRopeRopeBridgeCopy({required RopeBridge that});

  RopeBridge crateApiRopeRopeBridgeCreate({required String initialText});

  BigInt crateApiRopeRopeBridgeFindLineEnd({
    required RopeBridge that,
    required BigInt offset,
  });

  BigInt crateApiRopeRopeBridgeFindLineStart({
    required RopeBridge that,
    required BigInt offset,
  });

  List<BiDiSegment> crateApiRopeRopeBridgeGetBidiSegmentsForLine({
    required RopeBridge that,
    required BigInt lineIndex,
  });

  List<BiDiSegment> crateApiRopeRopeBridgeGetBidiSegmentsInRange({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  });

  String crateApiRopeRopeBridgeGetText({required RopeBridge that});

  void crateApiRopeRopeBridgeInsert({
    required RopeBridge that,
    required BigInt charIdx,
    required String text,
  });

  BigInt crateApiRopeRopeBridgeLenChars({required RopeBridge that});

  BigInt crateApiRopeRopeBridgeLenLines({required RopeBridge that});

  String crateApiRopeRopeBridgeLine({
    required RopeBridge that,
    required BigInt lineIdx,
  });

  BigInt crateApiRopeRopeBridgeLineToChar({
    required RopeBridge that,
    required BigInt lineIdx,
  });

  TextDirection crateApiRopeRopeBridgePrimaryDirection({
    required RopeBridge that,
  });

  void crateApiRopeRopeBridgeRemove({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  });

  String crateApiRopeRopeBridgeSlice({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  });

  TextDirection crateApiRopeRopeBridgeTextDirection({required RopeBridge that});

  Future<List<RustFoldRange>> crateApiEditorFoldsComputeAll({
    required RopeBridge rope,
  });

  PlatformInt64 crateApiEditorFoldsFindMatchingBracket({
    required RopeBridge rope,
    required int targetOffset,
  });

  List<GuideBlock> crateApiEditorGuidesComputeViewport({
    required RopeBridge rope,
    required BigInt firstVisible,
    required BigInt lastVisible,
    required BigInt tabSize,
  });

  Future<void> crateApiEditorInitApp();

  Future<LineSummary> crateApiEditorLineSummaryDefault();

  List<String> crateApiEditorWordsExtract({required RopeBridge rope});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LayoutMap;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LayoutMap;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LayoutMapPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RopeBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RopeBridge;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RopeBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiEditorLayoutMapClear({required LayoutMap that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorLayoutMapClearConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorLayoutMapClearConstMeta =>
      const TaskConstMeta(debugName: "LayoutMap_clear", argNames: ["that"]);

  @override
  LayoutMap crateApiEditorLayoutMapNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorLayoutMapNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorLayoutMapNewConstMeta =>
      const TaskConstMeta(debugName: "LayoutMap_new", argNames: []);

  @override
  void crateApiEditorLayoutMapPushLine({
    required LayoutMap that,
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
            that,
            serializer,
          );
          sse_encode_usize(lenChars, serializer);
          sse_encode_f_32(height, serializer);
          sse_encode_bool(isFolded, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorLayoutMapPushLineConstMeta,
        argValues: [that, lenChars, height, isFolded],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorLayoutMapPushLineConstMeta =>
      const TaskConstMeta(
        debugName: "LayoutMap_push_line",
        argNames: ["that", "lenChars", "height", "isFolded"],
      );

  @override
  List<String> crateApiRopeRopeBridgeCachedLines({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCachedLinesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCachedLinesConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_cached_lines",
        argNames: ["that"],
      );

  @override
  List<String> crateApiRopeRopeBridgeCachedLinesRange({
    required RopeBridge that,
    required BigInt startLine,
    required BigInt endLine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(startLine, serializer);
          sse_encode_usize(endLine, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCachedLinesRangeConstMeta,
        argValues: [that, startLine, endLine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCachedLinesRangeConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_cached_lines_range",
        argNames: ["that", "startLine", "endLine"],
      );

  @override
  String crateApiRopeRopeBridgeCharAt({
    required RopeBridge that,
    required BigInt position,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(position, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCharAtConstMeta,
        argValues: [that, position],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCharAtConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_char_at",
        argNames: ["that", "position"],
      );

  @override
  BigInt crateApiRopeRopeBridgeCharToLine({
    required RopeBridge that,
    required BigInt charIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(charIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCharToLineConstMeta,
        argValues: [that, charIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCharToLineConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_char_to_line",
        argNames: ["that", "charIdx"],
      );

  @override
  RopeBridge crateApiRopeRopeBridgeCopy({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCopyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCopyConstMeta =>
      const TaskConstMeta(debugName: "RopeBridge_copy", argNames: ["that"]);

  @override
  RopeBridge crateApiRopeRopeBridgeCreate({required String initialText}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(initialText, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeCreateConstMeta,
        argValues: [initialText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeCreateConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_create",
        argNames: ["initialText"],
      );

  @override
  BigInt crateApiRopeRopeBridgeFindLineEnd({
    required RopeBridge that,
    required BigInt offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeFindLineEndConstMeta,
        argValues: [that, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeFindLineEndConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_find_line_end",
        argNames: ["that", "offset"],
      );

  @override
  BigInt crateApiRopeRopeBridgeFindLineStart({
    required RopeBridge that,
    required BigInt offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeFindLineStartConstMeta,
        argValues: [that, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeFindLineStartConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_find_line_start",
        argNames: ["that", "offset"],
      );

  @override
  List<BiDiSegment> crateApiRopeRopeBridgeGetBidiSegmentsForLine({
    required RopeBridge that,
    required BigInt lineIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(lineIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bi_di_segment,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeGetBidiSegmentsForLineConstMeta,
        argValues: [that, lineIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeGetBidiSegmentsForLineConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_get_bidi_segments_for_line",
        argNames: ["that", "lineIndex"],
      );

  @override
  List<BiDiSegment> crateApiRopeRopeBridgeGetBidiSegmentsInRange({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(start, serializer);
          sse_encode_usize(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bi_di_segment,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeGetBidiSegmentsInRangeConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeGetBidiSegmentsInRangeConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_get_bidi_segments_in_range",
        argNames: ["that", "start", "end"],
      );

  @override
  String crateApiRopeRopeBridgeGetText({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeGetTextConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeGetTextConstMeta =>
      const TaskConstMeta(debugName: "RopeBridge_get_text", argNames: ["that"]);

  @override
  void crateApiRopeRopeBridgeInsert({
    required RopeBridge that,
    required BigInt charIdx,
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(charIdx, serializer);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeInsertConstMeta,
        argValues: [that, charIdx, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeInsertConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_insert",
        argNames: ["that", "charIdx", "text"],
      );

  @override
  BigInt crateApiRopeRopeBridgeLenChars({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeLenCharsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeLenCharsConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_len_chars",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRopeRopeBridgeLenLines({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeLenLinesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeLenLinesConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_len_lines",
        argNames: ["that"],
      );

  @override
  String crateApiRopeRopeBridgeLine({
    required RopeBridge that,
    required BigInt lineIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(lineIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeLineConstMeta,
        argValues: [that, lineIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeLineConstMeta => const TaskConstMeta(
    debugName: "RopeBridge_line",
    argNames: ["that", "lineIdx"],
  );

  @override
  BigInt crateApiRopeRopeBridgeLineToChar({
    required RopeBridge that,
    required BigInt lineIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(lineIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeLineToCharConstMeta,
        argValues: [that, lineIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeLineToCharConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_line_to_char",
        argNames: ["that", "lineIdx"],
      );

  @override
  TextDirection crateApiRopeRopeBridgePrimaryDirection({
    required RopeBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_direction,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgePrimaryDirectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgePrimaryDirectionConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_primary_direction",
        argNames: ["that"],
      );

  @override
  void crateApiRopeRopeBridgeRemove({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(start, serializer);
          sse_encode_usize(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeRemoveConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_remove",
        argNames: ["that", "start", "end"],
      );

  @override
  String crateApiRopeRopeBridgeSlice({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(start, serializer);
          sse_encode_usize(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeSliceConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeSliceConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_slice",
        argNames: ["that", "start", "end"],
      );

  @override
  TextDirection crateApiRopeRopeBridgeTextDirection({
    required RopeBridge that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_direction,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRopeRopeBridgeTextDirectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRopeRopeBridgeTextDirectionConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_text_direction",
        argNames: ["that"],
      );

  @override
  Future<List<RustFoldRange>> crateApiEditorFoldsComputeAll({
    required RopeBridge rope,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_fold_range,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorFoldsComputeAllConstMeta,
        argValues: [rope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorFoldsComputeAllConstMeta =>
      const TaskConstMeta(debugName: "folds_compute_all", argNames: ["rope"]);

  @override
  PlatformInt64 crateApiEditorFoldsFindMatchingBracket({
    required RopeBridge rope,
    required int targetOffset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          sse_encode_i_32(targetOffset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorFoldsFindMatchingBracketConstMeta,
        argValues: [rope, targetOffset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorFoldsFindMatchingBracketConstMeta =>
      const TaskConstMeta(
        debugName: "folds_find_matching_bracket",
        argNames: ["rope", "targetOffset"],
      );

  @override
  List<GuideBlock> crateApiEditorGuidesComputeViewport({
    required RopeBridge rope,
    required BigInt firstVisible,
    required BigInt lastVisible,
    required BigInt tabSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          sse_encode_usize(firstVisible, serializer);
          sse_encode_usize(lastVisible, serializer);
          sse_encode_usize(tabSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_guide_block,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorGuidesComputeViewportConstMeta,
        argValues: [rope, firstVisible, lastVisible, tabSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorGuidesComputeViewportConstMeta =>
      const TaskConstMeta(
        debugName: "guides_compute_viewport",
        argNames: ["rope", "firstVisible", "lastVisible", "tabSize"],
      );

  @override
  Future<void> crateApiEditorInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<LineSummary> crateApiEditorLineSummaryDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_line_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorLineSummaryDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorLineSummaryDefaultConstMeta =>
      const TaskConstMeta(debugName: "line_summary_default", argNames: []);

  @override
  List<String> crateApiEditorWordsExtract({required RopeBridge rope}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorWordsExtractConstMeta,
        argValues: [rope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorWordsExtractConstMeta =>
      const TaskConstMeta(debugName: "words_extract", argNames: ["rope"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LayoutMap => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LayoutMap => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RopeBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RopeBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge;

  @protected
  LayoutMap
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LayoutMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LayoutMap
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LayoutMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LayoutMap
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LayoutMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BiDiSegment dco_decode_bi_di_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BiDiSegment(
      start: dco_decode_usize(arr[0]),
      end: dco_decode_usize(arr[1]),
      direction: dco_decode_text_direction(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GuideBlock dco_decode_guide_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GuideBlock(
      startLine: dco_decode_i_32(arr[0]),
      endLine: dco_decode_i_32(arr[1]),
      indentLevel: dco_decode_i_32(arr[2]),
      leadingSpaces: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LineSummary dco_decode_line_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LineSummary(
      lenChars: dco_decode_usize(arr[0]),
      height: dco_decode_f_32(arr[1]),
      lines: dco_decode_usize(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BiDiSegment> dco_decode_list_bi_di_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bi_di_segment).toList();
  }

  @protected
  List<GuideBlock> dco_decode_list_guide_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_guide_block).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustFoldRange> dco_decode_list_rust_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_fold_range).toList();
  }

  @protected
  RustFoldRange dco_decode_rust_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustFoldRange(
      startLine: dco_decode_i_32(arr[0]),
      endLine: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  TextDirection dco_decode_text_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TextDirection.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  LayoutMap
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LayoutMapImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RopeBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LayoutMap
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LayoutMapImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RopeBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LayoutMap
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LayoutMapImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RopeBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BiDiSegment sse_decode_bi_di_segment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_usize(deserializer);
    var var_end = sse_decode_usize(deserializer);
    var var_direction = sse_decode_text_direction(deserializer);
    return BiDiSegment(
      start: var_start,
      end: var_end,
      direction: var_direction,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GuideBlock sse_decode_guide_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_i_32(deserializer);
    var var_endLine = sse_decode_i_32(deserializer);
    var var_indentLevel = sse_decode_i_32(deserializer);
    var var_leadingSpaces = sse_decode_i_32(deserializer);
    return GuideBlock(
      startLine: var_startLine,
      endLine: var_endLine,
      indentLevel: var_indentLevel,
      leadingSpaces: var_leadingSpaces,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LineSummary sse_decode_line_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lenChars = sse_decode_usize(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_lines = sse_decode_usize(deserializer);
    return LineSummary(
      lenChars: var_lenChars,
      height: var_height,
      lines: var_lines,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BiDiSegment> sse_decode_list_bi_di_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BiDiSegment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bi_di_segment(deserializer));
    }
    return ans_;
  }

  @protected
  List<GuideBlock> sse_decode_list_guide_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GuideBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_guide_block(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustFoldRange> sse_decode_list_rust_fold_range(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustFoldRange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_fold_range(deserializer));
    }
    return ans_;
  }

  @protected
  RustFoldRange sse_decode_rust_fold_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_i_32(deserializer);
    var var_endLine = sse_decode_i_32(deserializer);
    return RustFoldRange(startLine: var_startLine, endLine: var_endLine);
  }

  @protected
  TextDirection sse_decode_text_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TextDirection.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    LayoutMap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LayoutMapImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    LayoutMap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LayoutMapImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLayoutMap(
    LayoutMap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LayoutMapImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bi_di_segment(BiDiSegment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.start, serializer);
    sse_encode_usize(self.end, serializer);
    sse_encode_text_direction(self.direction, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_guide_block(GuideBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.startLine, serializer);
    sse_encode_i_32(self.endLine, serializer);
    sse_encode_i_32(self.indentLevel, serializer);
    sse_encode_i_32(self.leadingSpaces, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_line_summary(LineSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.lenChars, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_usize(self.lines, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bi_di_segment(
    List<BiDiSegment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bi_di_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_guide_block(
    List<GuideBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_guide_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_fold_range(
    List<RustFoldRange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_fold_range(item, serializer);
    }
  }

  @protected
  void sse_encode_rust_fold_range(
    RustFoldRange self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.startLine, serializer);
    sse_encode_i_32(self.endLine, serializer);
  }

  @protected
  void sse_encode_text_direction(TextDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LayoutMapImpl extends RustOpaque implements LayoutMap {
  // Not to be used by end users
  LayoutMapImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LayoutMapImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LayoutMap,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LayoutMap,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LayoutMapPtr,
  );

  void clear() => RustLib.instance.api.crateApiEditorLayoutMapClear(that: this);

  void pushLine({
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  }) => RustLib.instance.api.crateApiEditorLayoutMapPushLine(
    that: this,
    lenChars: lenChars,
    height: height,
    isFolded: isFolded,
  );
}

@sealed
class RopeBridgeImpl extends RustOpaque implements RopeBridge {
  // Not to be used by end users
  RopeBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RopeBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RopeBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeBridgePtr,
  );

  List<String> cachedLines() =>
      RustLib.instance.api.crateApiRopeRopeBridgeCachedLines(that: this);

  List<String> cachedLinesRange({
    required BigInt startLine,
    required BigInt endLine,
  }) => RustLib.instance.api.crateApiRopeRopeBridgeCachedLinesRange(
    that: this,
    startLine: startLine,
    endLine: endLine,
  );

  String charAt({required BigInt position}) => RustLib.instance.api
      .crateApiRopeRopeBridgeCharAt(that: this, position: position);

  BigInt charToLine({required BigInt charIdx}) => RustLib.instance.api
      .crateApiRopeRopeBridgeCharToLine(that: this, charIdx: charIdx);

  RopeBridge copy() =>
      RustLib.instance.api.crateApiRopeRopeBridgeCopy(that: this);

  BigInt findLineEnd({required BigInt offset}) => RustLib.instance.api
      .crateApiRopeRopeBridgeFindLineEnd(that: this, offset: offset);

  BigInt findLineStart({required BigInt offset}) => RustLib.instance.api
      .crateApiRopeRopeBridgeFindLineStart(that: this, offset: offset);

  List<BiDiSegment> getBidiSegmentsForLine({required BigInt lineIndex}) =>
      RustLib.instance.api.crateApiRopeRopeBridgeGetBidiSegmentsForLine(
        that: this,
        lineIndex: lineIndex,
      );

  List<BiDiSegment> getBidiSegmentsInRange({
    required BigInt start,
    required BigInt end,
  }) => RustLib.instance.api.crateApiRopeRopeBridgeGetBidiSegmentsInRange(
    that: this,
    start: start,
    end: end,
  );

  String getText() =>
      RustLib.instance.api.crateApiRopeRopeBridgeGetText(that: this);

  void insert({required BigInt charIdx, required String text}) => RustLib
      .instance
      .api
      .crateApiRopeRopeBridgeInsert(that: this, charIdx: charIdx, text: text);

  BigInt lenChars() =>
      RustLib.instance.api.crateApiRopeRopeBridgeLenChars(that: this);

  BigInt lenLines() =>
      RustLib.instance.api.crateApiRopeRopeBridgeLenLines(that: this);

  String line({required BigInt lineIdx}) => RustLib.instance.api
      .crateApiRopeRopeBridgeLine(that: this, lineIdx: lineIdx);

  BigInt lineToChar({required BigInt lineIdx}) => RustLib.instance.api
      .crateApiRopeRopeBridgeLineToChar(that: this, lineIdx: lineIdx);

  TextDirection primaryDirection() =>
      RustLib.instance.api.crateApiRopeRopeBridgePrimaryDirection(that: this);

  void remove({required BigInt start, required BigInt end}) => RustLib
      .instance
      .api
      .crateApiRopeRopeBridgeRemove(that: this, start: start, end: end);

  String slice({required BigInt start, required BigInt end}) => RustLib
      .instance
      .api
      .crateApiRopeRopeBridgeSlice(that: this, start: start, end: end);

  TextDirection textDirection() =>
      RustLib.instance.api.crateApiRopeRopeBridgeTextDirection(that: this);
}
