// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rope.dart';

// These functions are ignored because they are not marked as `pub`: `contains_same_tag_closing`, `contains_same_tag_opening`, `extract_opening_tag_name`, `find_matching_bracket_in_rope`, `find_matching_closing_tag_line`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LineBlock`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `add_summary`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `summary`, `zero`

Future<List<RustFoldRange>> foldsComputeAll({required RopeBridge rope}) =>
    RustLib.instance.api.crateApiEditorFoldsComputeAll(rope: rope);

PlatformInt64 foldsFindMatchingBracket({
  required RopeBridge rope,
  required int targetOffset,
}) => RustLib.instance.api.crateApiEditorFoldsFindMatchingBracket(
  rope: rope,
  targetOffset: targetOffset,
);

List<GuideBlock> guidesComputeViewport({
  required RopeBridge rope,
  required BigInt firstVisible,
  required BigInt lastVisible,
  required BigInt tabSize,
}) => RustLib.instance.api.crateApiEditorGuidesComputeViewport(
  rope: rope,
  firstVisible: firstVisible,
  lastVisible: lastVisible,
  tabSize: tabSize,
);

List<String> wordsExtract({required RopeBridge rope}) =>
    RustLib.instance.api.crateApiEditorWordsExtract(rope: rope);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LayoutMap>>
abstract class LayoutMap implements RustOpaqueInterface {
  void clear();

  factory LayoutMap() => RustLib.instance.api.crateApiEditorLayoutMapNew();

  void pushLine({
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  });
}

class GuideBlock {
  final int startLine;
  final int endLine;
  final int indentLevel;
  final int leadingSpaces;

  const GuideBlock({
    required this.startLine,
    required this.endLine,
    required this.indentLevel,
    required this.leadingSpaces,
  });

  @override
  int get hashCode =>
      startLine.hashCode ^
      endLine.hashCode ^
      indentLevel.hashCode ^
      leadingSpaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuideBlock &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine &&
          indentLevel == other.indentLevel &&
          leadingSpaces == other.leadingSpaces;
}

class LineSummary {
  final BigInt lenChars;
  final double height;
  final BigInt lines;

  const LineSummary({
    required this.lenChars,
    required this.height,
    required this.lines,
  });

  static Future<LineSummary> default_() =>
      RustLib.instance.api.crateApiEditorLineSummaryDefault();

  @override
  int get hashCode => lenChars.hashCode ^ height.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineSummary &&
          runtimeType == other.runtimeType &&
          lenChars == other.lenChars &&
          height == other.height &&
          lines == other.lines;
}

class RustFoldRange {
  final int startLine;
  final int endLine;

  const RustFoldRange({required this.startLine, required this.endLine});

  @override
  int get hashCode => startLine.hashCode ^ endLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustFoldRange &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine;
}
